### ISSUE TITLE
Event call.

### ISSUE THREAD

**Issue by Tagoff** [ikkentim/SampSharp#233]
Let's assume I want to use an event from one class to another, a craze that I use as a modular programming.

When a player enters, he would be in first class. When the player selects TextDraw, the event would be triggered in the Record or Login class, depending on which of the two it selects.

Last time, before I deleted my other gamemode, I had done more or less the same, before I started to show some bizarre bugs with the events.

As I like to separate in modular programming, this model below, is correct?

The first class.
**PS: The LabelLogin is inside of the Usuario class. ([PooledType])**

`playerid.LabelLogin.Click += new Registro(playerid).TextDrawRegistroSelecionado;`

**PS: Usuario is a local of all variables of the players, it is in [PooledType]**

The second class.
````
class Registro
    {
        private Usuario playerid = null;
        public Registro(Usuario playerid)
        {
            this.playerid = playerid;
            SAConsole.SendLine(ConsoleColor.Green, $"[Registro]: Player {playerid.Name}[{playerid.Id}] de IP: {playerid.IP} está registrando-se !");
        }

        public void TextDrawRegistroSelecionado(object sender, SampSharp.GameMode.Events.ClickPlayerTextDrawEventArgs e)
        {
            playerid.LabelIntro.Hide();
            playerid.LabelLogin.Hide();
            playerid.LabelRegistro.Hide();

        }
    }
````

**Comment by ikkentim** [comment]
For one thing you're using the variable name `playerid` wrong. playerid stands for player identifier, where identifier means "a number which identifies a player". The variable name you should really be using here is `player`.

Here's an example of how you could create a basic registration module. Please note I can't compile or test this code at this moment:

```
class RegistrationService
{
  TextDraw _textDraw; // a universal text draw, same for each player.
  public RegistrationService()
  {
    _textDraw = new TextDraw(/* ... */);
    // TODO: Set up the text draw.
    _textDraw.Click += TextDrawClick;
  }

  private void TextDrawClick(object sender, ClickTextDrawEventArgs e)
  {
    // TODO: Handle click
  }

  public void Show(Player player)
  {
    _textDraw.Show(player);
  }
}
```

You simply need to instantiate this service once the game mode starts.

If you NEED to use PlayerTextDraws, because you need to show personalized information, you can either store it in the player instance, or you could store it in a dictionary. If you do store it in a dictionary, make sure to remove it when the player disconnects (using the player.Disconnected event).

**Comment by Tagoff** [comment]
I always forget to use the correct name of player, a craze since i've programmed in pawn kk 

Only another question, what will happens if the player disconnect from the server upon created the instance? because i use the Disposed interface when the player finishes registering, but what will happens if the player leave ?

**Comment by ikkentim** [comment]
The player and player textdraws will be automatically disposed, other resources should be cleaned up manually.
