### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by hottabych07** [ikkentim/SampSharp#265]
@ikkentim A big request, from all, please complete Wiki(for 0.8 alpha). http://alpha.sampsharp.timpotze.nl/

**Comment by ikkentim** [comment]
It's my 2nd highest priority after performance improvements. It's really needed yea 👍

**Comment by moono-samp** [comment]
@ikkentim  Do you plan to implement multilanguage documentation?

**Comment by ikkentim** [comment]
No, keeping 1 language of docs up to date is more than enough work

**Comment by Zelyutin** [comment]
Is there a chance that docs will be able to be translated and placed on the docs website as another language version in the future?
I mean, Streamer, has English and Russian version at github wiki.
S# website is build on your WikiClone solution.
So, is it possible to add language switcher to the site based on wiki pages with language affix somehow?
E.g. streamer has now samp-streamer-plugin/wiki/Natives and samp-streamer-plugin/wiki/Natives-RU (imaging samp-streamer-plugin/wiki/Natives-ES, samp-streamer-plugin/wiki/Natives-FR and so on).

When 0.8 docs appear, I would be very glad to help the project to attract non-english-speaking russian community, translating it to the russian.
Because S# is really giant thing, that raises up samp modes development to incredibly new level.

**Comment by Zelyutin** [comment]
Glad to hear it! 
Yes, thanks, I've got it after previous reply while learning new docs that you already made. Also, I've made a pull request for 0.7 docs there similar to update I made in wiki.

**Comment by ikkentim** [comment]
Closing this since docs have their own repository.
