### ISSUE TITLE
Translating command parameter names

### ISSUE THREAD

**Issue by Zelyutin** [ikkentim/SampSharp#269]
I wish the support for translating command parameres names will be implemented in the future. So everyone can have fully translated Usage message, not only the template.

**Comment by moono-samp** [comment]
What do you mean? Than this option is bad?
`[Command("goto", UsageMessage="Используйте: /goto [ID или имя игрока]")]`

**Comment by ikkentim** [comment]
I'll be looking into providing a custom formatting function for the usage message, and a way of translating the parameter names to a local language.

**Comment by ikkentim** [comment]
I won't be building a more convenient way to do this as it would take more time than I'd like to spend on SampSharp.GameMode and since there's already a way to do this:

This can be done by overriding the `bool SendUsageMessage(BasePlayer player)` method from `DefaultCommand`. See https://sampsharp.net/player-commands#overriding-default-behavior for information on overriding default command behavior.
