### ISSUE TITLE
GameModeExitBehaviour.ShutDown is not working for me in Ubuntu

### ISSUE THREAD

**Issue by SaSiNO97** [ikkentim/SampSharp#322]
GameModeExitBehaviour.ShutDown is not working for me in Ubuntu Server 18.04, when I send a rcon exit to the SA-MP Server, the .NET Core process remains waiting for a reconnect.

**Comment by ikkentim** [comment]
Currently on vacation, will check when I’m back.

**Comment by SaSiNO97** [comment]
Good for you 👍 , have a great vacation 😄

**Comment by ikkentim** [comment]
It's been a while...

I tried to reproduce this bug but I can't get the same thing to happen.

The multi process run mode is for debugging purposes anyways, and it's more for restarting/stopping the game mode rather than the SA-MP server so I'm not too worried if specifically that functionality doesn't work on Linux.


Let me know if you are still having problems with this.
