### ISSUE TITLE
Command overloading stopped working properly

### ISSUE THREAD

**Issue by SaSiNO97** [ikkentim/SampSharp#344]
Command overloading used to work fine, but after updating to the latest SampSharp version, only the first version of a command is being recognized.

The following code:
```
[Command("rob", "rb")]
private void RobCommand(Player victim) // Player is a subclass of BasePlayer
{
    // omitted
}

[Command("rob", "rb")]
private void RobCommand()
{
    // omitted
}
```

Outputs:

```Usage: /rob [victim]```

If the players types `/rob` without specifying the victim parameter.

**Comment by ikkentim** [comment]
In what version did it last work?

**Comment by SaSiNO97** [comment]
I migrated from Core 0.9.0 and GameMode 0.9.0 to Core 0.9.3 and GameMode 0.9.1 about 2 months ago. I didn't immediately notice the issue, and other changes were made meanwhile, in fact I also moved from .NET Core 2.2 to 3.1.

**Comment by SaSiNO97** [comment]
New info, now that I have rolled back to 0.9.0, it looks the command overloading is still not working properly, so I assume that the feature could have stopped working when I migrated from 0.8.0.

**Comment by ikkentim** [comment]
Thanks, I’ll check what I changed between those releases.

**Comment by ikkentim** [comment]
Fixed this particular issue... SampSharp is still a bit bad at deciding what to do when no valid parameters are provided, for example when commands `/foo` and `/foo [player]` exists, when the player enters `/foo 9` (id 9 is not connected), it will invoke `/foo` instead of `/foo [player]` further command improvements are planned for a future update.
