### ISSUE TITLE
Is it safe to save stats in OnExited method?

### ISSUE THREAD

**Issue by MrDave1999** [ikkentim/SampSharp#367]
As you can see, the current player stats can be lost if the server is unexpectedly restarted or shut down. So I was thinking of saving the stats for each player when the OnExited method is called.

Is it safe to save the data there? Or is it possible that not all the data is saved?
PS: Sorry if you don't understand me, I don't speak English.

**Comment by CiprianN23** [comment]
I would suggest to save stats as they change. Eg: Server give player named Test 100$, server makes a query to database to save player Test its money

This would be the better approach to keep the data loss as close to 0 as possible. Only issue i see saving stats on `OnExited` is that it might no longer contains some data because Player object could be already disposed. This is my opinion

**Comment by ikkentim** [comment]
To prevent dataloss, do the above.

You can save data OnExited, but you can't use async, unless you won't be accessing any (player)natives anymore. After an await call in OnExited, it is likely the player has fully disconnected, and the player object will be disposed.
