### ISSUE TITLE
Detect commands in player classes

### ISSUE THREAD

**Issue by ikkentim** [ikkentim/SampSharp#92]
Example:
```
In player.cs
[Command("sayhi")]
public void hi()
{
    SendClientMessageToAll(SampSharp.GameMode.SAMP.Color.Red, "Player {0} say hi!", this.Name);
}
```

**Comment by Dolfik1** [comment]
It's looks cool :)

**Comment by rrev** [comment]
Well, it should be noted that a method (command) needs to be static otherwise RegisterCommands ignores it.

A question:

How should we be handle the case where the method args are:

```
public void hi(GtaPlayer hi) {

}
```

inside a class which is compatible with `GtaPlayer`? It should be read like:

1. The first argument is a parameter (example /hi <player_name>)
2. It's just the programmer that don't like (don't know) the GtaPlayer-instance inference so it's still the old syntax

My first implementation is like:

- Get the Declaring class of the command / method
- Check if it's compatible with GtaPlayer
- If it's not compatible use the old if to check if the first argument is a GtaPlayer param
- (>> here the problem <<) If it's compatible, check if the first argument is still a GtaPlayer... what to do now? Shall we forget it? 

All this with an int variable `parametersToSkip` used inside the LINQ 

    Command.GetParameters()
           .Skip(1)

where it will be 1 if it should skip the first argument (so GtaPlayer) or 0 in case it shouldn't

**Comment by ikkentim** [comment]
@rrev: It's very simple: 

When attempting to call a command...
```
find method with 'Command' attribute matching the command name
if method is static
    call as usual
else if class_of_method is inheriting player class
    find player that called the command
    call player.command_method(parameters)
endif
```
